name: sparkdb
services:
  db:
    image: postgres:16.4
    container_name: ${SPARKDB_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${SPARKDB_DATABASE_NAME}
      POSTGRES_USER: ${SPARKDB_DATABASE_USER}
      POSTGRES_PASSWORD: ${SPARKDB_DATABASE_PASSWORD}
    ports:
      - "127.0.0.1:5000:5432"
    volumes:
      - /srv/pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - spark

networks:
  spark:
    external: true