name: sparkdb
services:
  db:
    image: postgres:16.4
    container_name: sparkdb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5000:5432"
    volumes:
      - /srv/pg_data:/var/lib/postgresql/data
    networks:
      - spark

networks:
  spark:
    external: true