name: postgresDB
services:
  db:
    image: postgres:16.4
    container_name: postgresDB
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5000:5432"
    volumes:
      - /srv/pg_data:/var/lib/postgresql/data
